parent: hummingbird-test
namne: hummingbird-child
display_name: Hummingbird Child
version: 1.0.0
author:
  name: "Raphael Mourouzidis"
  email: "rafasmour@gmail.com"
  url: ""

assets:
  use_parent_assets: true
